### ISSUE TITLE
Help with responsive elements 

### ISSUE THREAD

**Issue by sara-clayton2** [sara-clayton2/dsn1676-assignment1#1]
Hi thomas, 
so my website works when it is in large small and small screen but medium screen isn't responsive. When i go into medium screen everything just squishes together. help please! 

http://sara-clayton2.github.io/dsn1676-assignment1

@thomasjbradley

**Comment by thomasjbradley** [comment]
I can see two things that may help you:
1. Here, on this line of code, you have the class `.img-flex`, but it's missing from your CSS:
   https://github.com/sara-clayton2/dsn1676-assignment1/blob/gh-pages/index.html#L28
2. The `.box` class has a width on it that seems to be interfereing:
   https://github.com/sara-clayton2/dsn1676-assignment1/blob/gh-pages/css/main.css#L82
